AutoScalingGroup:
  Type: AWS::AutoScaling::AutoScalingGroup
  Properties: ...
  UpdatePolicy:
    AutoScalingRollingUpdate:
      MaxBatchSize: '2'
      MinInstancesInService: '1'
      PauseTime: PT10M
      SuspendProcesses:
      - AlarmNotification
      WaitOnResourceSignals: true