---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Hello World! example'
Parameters:
  VPC:
    Description: 'The default VPC'
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: 'A subnet from default VPC.'
    Type: AWS::EC2::Subnet::Id
  SubnetType:
    Description: 'Choose the type of the subnet.'
    Type: String
    AllowedValues:
    - 'Private'
    - 'Public'
Conditions:
  HasPublicSubnet: !Equals [!Ref SubnetType, 'Public']
Mappings:
  RegionMap:
    eu-west-1:
      AMI: ami-bff32ccc
    ap-southeast-1:
      AMI: ami-c9b572aa
    ap-southeast-2:
      AMI: ami-48d38c2b
    eu-central-1:
      AMI: ami-bc5b48d0
    ap-northeast-2:
      AMI: ami-249b554a
    ap-northeast-1:
      AMI: ami-383c1956
    us-east-1:
      AMI: ami-60b6c60a
    sa-east-1:
      AMI: ami-6817af04
    us-west-1:
      AMI: ami-d5ea86b5
    us-west-2:
      AMI: ami-f0091d91
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: t2.micro
      NetworkInterfaces:
      - AssociatePublicIpAddress: !If [HasPublicSubnet, 'true', 'false']
        DeviceIndex: '0'
        GroupSet: 
        - !Ref WebserverSecurityGroup
        SubnetId: !Ref Subnet
      Tags:
      - Key: Name
        Value: hello-world
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          yum install -y httpd
          cd /var/www/html
          echo "<html><body>Hello World!</body></html>" > index.html
          service httpd start
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: hello-world-webserver
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
Outputs:
  HelloWorldURL:
    Description: The URL pointing to Hello World!.
    Value: !If [HasPublicSubnet, !Sub 'http://${EC2Instance.PublicIp}', !Sub 'http://${EC2Instance.PrivateIp}']
  
